### ISSUE TITLE
Certificate management & usage

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd-operator#10]
Refer to the [Spec & design](https://docs.google.com/document/d/1k8os77Hqxe36nUaZ31YqBGBuXcgdozVPppJYOfwUDFA/edit?tab=t.0).

## Tasks breakdown
- [ ] Mount secrets into etcd PODs
       From etcd POD perspective, it doesn't care about how the secrets/certificates are generated, it just mounts the secret and use the certificates directly.
    - [ ] Extend the CRD definition to include certificate, similar to https://github.com/etcd-io/etcd-operator/pull/9#discussion_r1873917550
    - [ ] Update reconciliation workflow to mount the secrets into etcd POD. Blocked by the reconciliation work.
    - [ ] Users are supposed to get the secretes/certificates prepared before creating etcd clusters. We need to clearly document this.
        - [ ] Users can manually create & manage the secrets & certificates themselves. 
        - [ ] etcd-operator can try to implement some utilities to manage secrets & certificates (see next section)
- [ ] etcd-operator supports certificate management
    - [ ] Define an interface, so that users can extend or integrate their own certificate service with the etcd-operator.
        - Note etcd-operator's priority is to simplify & automate the management of the etcd clusters instead of certificate management. 
    - [ ] Implement some simple certificate management utilities for testing purpose, 
        - [ ]  i.e. supporting auto self-signed certificate.
    - [ ] Investigate some best practice & popular certificate issuers to handle certificate management, and decide the next step.

References:
- https://docs.google.com/document/d/1k8os77Hqxe36nUaZ31YqBGBuXcgdozVPppJYOfwUDFA/edit?tab=t.0
- https://github.com/etcd-io/etcd-operator/pull/59

**Comment by gdasson** [comment]
@ahrtr : Can you please assign me? I'll start working on it from next week. Thanks.

**Comment by ahrtr** [comment]
Thanks @gdasson . Previously @ArkaSaha30 was working on this task. But since there isn't much progress so far,  we don't have much time to wait, so assigned this task to both of you.
